Ai mode
nastiche/taskifai pull request #16
Opened 2023-06-27 10:42 UTC by nastiche

2023-06-27 14:39 UTC, dimitriosxmi commented on pages/api/tasks/ai/index.js
> +    console.log(aiTaskData);
`console.log()`

2023-06-27 14:40 UTC, dimitriosxmi commented on pages/create.js
> +  console.log(aiTaskDescription);
`console.log()`

2023-06-27 18:15 UTC, nastiche commented on pages/api/tasks/index.js
> +      await
der Rest des codes ist im PR nicht zu sehen, sonst macht es Sinn:

if (request.method === "POST") {
    try {
      const taskData = request.body;
      await Task.create(taskData);
      await response.status(201).json({ status: "Task created" });
    } catch (error) {
      console.log(error);
      response.status(400).json({ error: error.message });
    }
  }

2023-06-27 18:16 UTC, nastiche commented on pages/api/tasks/ai/index.js
> +    console.log(aiTaskData);
will fix

2023-06-27 18:16 UTC, nastiche commented on pages/create.js
> +  console.log(aiTaskDescription);
will fix

2023-06-29 13:07 UTC, actyvystom requested changes
Amazing loads of code lines! 🤯 
I picked a few simple issues but all in all these are far too many lines of code to get an overview in a reasonable time - although very nicely commented.  
As this is refactoring, I suggest to break it down into edible pieces (PRs).
Cheers, Thomas

2023-06-29 14:28 UTC, CarstenJahnke commented
Wooh, so much changes 😝🚀 LGTM

2023-06-29 14:32 UTC, merged